default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3
  # Movemos las variables específicas de SQLite aquí
  variables:
    journal_mode: WAL
    synchronous: NORMAL
    cache_size: -2000

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cable:
    <<: *primary_production
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production